### ISSUE TITLE
Tymly - Missing flobot-pg-plugin state tests

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#1]
The...

* exportingCsvDeltaFile
* importingCsvFiles
* synchronizingTable

...states, as defined in [flobot-pg-plugin](https://github.com/wmfs/tymly/tree/master/plugins/flobot-pg-plugin/lib/components/states) plugin are missing tests.

* As part of the last Sprint, we wrote a test Blueprint for this very reason... it needs bringing into the plugin tests too.

**Comment by meenahoda** [comment]
Added some tests in (https://github.com/wmfs/tymly/commit/9d839fab5ea29067cd62eaaf7e101ca6854e34ff).
For Importing CSV state it imports some animals with an age. For Synchronizing Table state, it transforms those rows to another table but with a 'year_born' column, calculated from the age from the first table.
