### ISSUE TITLE
Tymly - UUID columns need to have DEFAULT set to 'uuid_generate_v1()'.

### ISSUE THREAD

**Issue by meenahoda** [wmfs/tymly#10]
UUID columns need to have DEFAULT set to 'uuid_generate_v1()'. 
This should be done where the schemas/tables are being generated, possibly in relationize. Something like 'columnDefault': 'uuid_generate_v1()' on relationze/lib/parser.js:line130 maybe?

https://github.com/wmfs/tymly/blob/master/relationize/lib/parser.js#L130

**Comment by timneedham** [comment]
**Yup, that seems to be set-up OK @meenahoda !**

And this is where create/alter column statements get generated:

https://github.com/wmfs/tymly/blob/master/pg-diff-sync/lib/statement-generators/column/index.js#L25-L27

...so, not sure why UUID columns don't automatically get their default values added to the column?

Might be best if we introduce debugging throughout Relationize to get a handle with what's going on? 

Please see the work @lilianasj did in this commit... 

https://github.com/wmfs/tymly/commit/40e1349ac8b65a3880eb0f2b8846546408e605ec

...note we should configure the module to be "relationize", so `const debug = require('debug')('relationize')`. We'll also need to ensure `debug` is added to relationize's `package.json`.

**Comment by meenahoda** [comment]
the following are console.logs() of things showing the state of the 'id' throughout:

relationize\lib\parser.js :line 125
---------------------
content.properties.id = {
          'type': 'uuid',
          'description': 'Automatically added UUID-based primary key column',
          'columnDefault': 'uuid_generate_v1()'
        }


relationize\lib\parser.js :line 260
----------------------
id: 
      { array: false,
        dataType: 'uuid',
        isNullable: 'NO',
        comment: 'Automatically added UUID-based primary key column' },


pg-diff-sync\lib\statement-generators\column\index.js :line 31
---------------------
>>>>> tymly.watched_boards.id , { base: 
   { columnDefault: null,
     isNullable: 'NO',
     dataType: 'uuid',
     characterMaximumLength: null,
     numericScale: null,
     comment: 'Automatically added UUID-based primary key column',
     array: false },
  target: 
   { array: false,
     dataType: 'uuid',
     isNullable: 'NO',
     comment: 'Automatically added UUID-based primary key column' } } , []



CONCLUSION...
id loses the 'columnDefault' between lines 125 and 260 in relationize parser
at line 260 id wants to look like:
id: 
   { array: false,
     dataType: 'uuid',
     columnDefault: 'uuid_generate_v1()',
     isNullable: 'NO',
     comment: 'Automatically added UUID-based primary key column' },

**Comment by meenahoda** [comment]
Not a good fix... it broke the travis build ><

**Comment by meenahoda** [comment]
A better kind-of fix.....

if (columns.id && columns.id.dataType === 'uuid') {...}

tymly-pg-plugin had an id with the dataType = 'numeric' that was a problem
