### ISSUE TITLE
Refactor Smithereens DSL

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#4]
The [processingCsvFiles](https://github.com/wmfs/tymly/tree/master/plugins/flobot-etl-plugin/lib/components/states/processing-csv-files) state is working... but the underlying [Smithereens](https://github.com/wmfs/tymly/tree/master/smithereens) module can cause a lot of JSON duplication... as can be seen here:

https://github.com/wmfs/addressbase-plus-blueprint/blob/master/flows/import-csv-files.json#L13-L678

One of the key Tymly watchwords is "minimal". This currently isn't that. But we can make it a _bit_ better, quite easily.
 
In the case of Addressbase Plus at hand, we want the exact same `outputColumns` configuration for both records matching "U" and "I". 
 
As it stands, that's duplication of the highest order (2 x ~70 columns), which is a pain.
 
**So how to reduce that burden quickly, now?**
 
This is taken from the tests:

``` 
fileSplits: {
  columnIndex: 4,
  valueToFileMap: {
    'u': {
      filename: 'changes',
      outputColumns: [
        {name: 'person_no', columnIndex: 0},
        {name: 'first_name', columnIndex: 1},
        {name: 'last_name', columnIndex: 2}
      ]
    },
    'd': {
      filename: 'deletes',
      outputColumns: [
        {name: 'person_no', columnIndex: 0}
      ]
    }
  }
}
``` 
We can see that the when the incoming parsed-CSV array comes in, then element with at 4 (i.e. the fifth column in the CSV line)
And depending on that value, "u" or "d"... the associated `outputColumns` property is used to discern the output line content.
 
So in the case of Addressbase Plus, how can we define one set of `outputColumns`, to match both the "U" and "I" values... as to shepherd them both to an "upsert" file?
 
**Proposal**
 
By some fancy DSL shenanigans? By way of example, how about:
 
```
fileSplits: {
  columnIndex: 4,
  valueToFileMap: {
    'i&u': {
      filename: 'changes',
      outputColumns: [
        {name: 'person_no', columnIndex: 0},
        {name: 'first_name', columnIndex: 1},
        {name: 'last_name', columnIndex: 2}
      ]
    },
    'd': {
      filename: 'deletes',
      outputColumns: [
        {name: 'person_no', columnIndex: 0}
      ]
    }
  }
}
```
 
See the usage: `i&u` there... that works quite neatly?
 
It's quick to implement now, pretty-much halve's the config, keeps open future capabilities?
 
Let's try upgrading Smithereens to support that?
 
Where to start? Here?

https://github.com/wmfs/tymly/blob/master/smithereens/lib/File-builder.js#L52-L62

* `line` represents the incoming CSV line from a source file, as an array of values.
* `value` is the value identified by columnIndex (in the above example: 4)
* So, if that value exists as a key name in valueToFileMap object, then replace value what's in the map and return that.

So that's what we need to refactor, to support "`&`".

**Comment by meenahoda** [comment]
```
return function columnIndexFileInfo (line) {
      let value = line[columnIndex]
      let keys = _.keys(valueToFileMap)
      let matchingKey
      
      for(var key of keys) { // [ 'i&u', 'd' ]
        var splitKeys = key.split('&')
        for (var k of splitKeys) { // [ 'i', 'u', 'd' ]
          if (k === value) {
            matchingKey = key
          }
        }
      }
      if (valueToFileMap.hasOwnProperty(matchingKey)) {
        value = valueToFileMap[matchingKey]
      } else {
        value = {filename: UNKNOWN_FILENAME}
      }

      console.log('Action: ', line[columnIndex], ',', value.filename)
      return value
}
```

Something like this? It currently works locally with the smithereens tests.

**Comment by timneedham** [comment]
Closed by @meenahoda
