### ISSUE TITLE
Trailing semi-colon in plugin paths of environment variables causes error

### ISSUE THREAD

**Issue by meenahoda** [wmfs/tymly#43]
Add check to strip trailing/leading semi-colons at the end of the plugin path entry

**Comment by timneedham** [comment]
**Great!**

It's a usual suspect, the `path-exploder.js`:
https://github.com/wmfs/tymly/blob/master/packages/flobot/lib/boot/load/flobot-loader/path-exploder.js#L27

...so:

Each `rawPart` will need trimming of all leading/trailing whitespace.
And only if after that it's a string with `length > 0` should things go any further.

**Comment by reecebrend** [comment]
Does

`
const globbed = glob.sync(
            part,
            {}
          )

          if (globbed.length > 0) {
            globbed.forEach(
              function (dir) {
`
Not already do this?

**Comment by reecebrend** [comment]
Isn't this already handled here?
`const globbed = glob.sync(
            console.log('part after trim >>>>>>>>>>>>>>>>>>', part)
            part,
            {}
          )

          if (globbed.length > 0) {
            globbed.forEach(
              function (dir) {
...
          `

**Comment by meenahoda** [comment]
If you try to pass a plugin path with a trailing semi-colon, it will try to process a rawPart which has a length of 0. When it tries to path.normalize(rawPart) with a length of 0, it turns the empty string into a '.' and length of the string becomes 1.
I've put a condition to check if the trimmed rawPart has a length more than 0 before continuing:
if (rawPart.trim().length > 0) {...}
