### ISSUE TITLE
Statebox: Parallel States and aggregated results

### ISSUE THREAD

**Issue by pmotyka** [wmfs/tymly#452]
I'm trying to arrive at a set of results such that the results are aggregated from all the states being executed in parallel.  I've put together a test that attempts this and demonstrates that the results are seemingly only containing the data from the last specified state:  https://github.com/pmotyka/tymly/commit/2aa4f6351945b2b3e76052c2056acc4a98cbb08d.  From what I can tell via the Amazon States Language, the expected behavior here is to aggregate results: https://states-language.net/spec.html#parallel-state.  Please have a look and let me know if there's an issue here or if I'm attempting the aggregation of results incorrectly.

**Comment by reecebrend** [comment]
Hi @pmotyka,

Just to let you know this monorepo is now deprecated due to a change in our git architecture.
This package is still being supported but over at https://github.com/wmfs/statebox

We'll look into this when we get the chance 👍

**Comment by pmotyka** [comment]
Thanks for letting me know and for the quick fix on the issue!
