### ISSUE TITLE
Outdated documentation on Guide

### ISSUE THREAD

**Issue by BillMeyerRSA** [wmfs/tymly#455]
Minor Errors in documentation: https://wmfs.github.io/tymly-website/guide/#tymly-cli

blue-print create:

> From inside a throwaway directory somewhere, run the following command:
> 
> tymly new-blueprint
> You'll be prompted for a few details regarding your new digital service. For the purposes of this example specify the name tymly-pizza-blueprint.

When running the command, it gives error
```
_$ tymly new-blueprint
Usage: new-blueprint [options] <blueprint-name>

Create a new Tymly blueprint

Options:
  -p, --path <path>  working directory - defaults to "."
  -u, --use <path>   an existing blueprint to use as a base - use its models, roles, etc in the new blueprint
  --profile <path>   alternative profile path - defaults to your home directory
  -h, --help         output usage information

Missing required argument <blueprint-name>._
```
The command must include the blueprint name e.g.
tymly new-blueprint  tymly-pizza-blueprint

Then you will be prompted for 

- Blueprint namespace
- Description
- What kind of data will this blueprint work with?

**Comment by BillMeyerRSA** [comment]
Also error with adding model according to guide:
`$ tymly add-model --name pizza
Usage: add-model [options]

Add a new Tymly data model to a blueprint

Options:
  -p, --path <path>  blueprint directory - defaults to "."
  -h, --help         output usage information

Unknown option --name.
`
Has more options e.g. model properties, data types, Primary keys etc
`$ tymly add-model orders
✔ Model name · orders

Adding orders model to blueprint tymly-pizza-blueprint-1

✔ Model Title · Orders
✔ Model Description · Orders

Model properties:
✔ Property name · Orders
✔ Property Title · Orders
✔ Property Description · Orders
✔ Data category · text
✔ Data type · text
✔ Is Primary Key (y/N) · false
✔ Is Required (y/N) · false

? Property name ‣   (hit Enter to quit)
`

**Comment by BillMeyerRSA** [comment]
In documentation also some options are incorrect:

> $ tymly add editable --model pizza

must be

> tymly add-editable --model pizza

**Comment by BillMeyerRSA** [comment]
This command I cannot find any indication which one in the command list it must be

> tymly add creatable --model order

Command line gives these options:
```
Commands:
  init [options]                            Set up some details so you don't have to keep typing them
  new-blueprint [options] <blueprint-name>  Create a new Tymly blueprint
  add-model [options]                       Add a new Tymly data model to a blueprint
  add-editable [options]                    Scaffold a new form
  add-view [options]                        Scaffold a new view or board
  add-table [options]                       Scaffold a new table view
  add-category [options]                    Generate category
  add-role [options]                        Generate role
  add-state-machine [options]               Generate a new state machine
  add-search-doc [options]                  Scaffold a new search document
  add-function [options]                    Create a function skeleton

```

**Comment by BillMeyerRSA** [comment]
Is there perhaps a downloadable demo that is fully functional? 
Also running any Tymly dev command I get

- Unknown command dev

Seems like there was a lot of changes since the Tymly Guide and Reference was published and the latest available tymly install.

**Comment by martinelsner** [comment]
I second this. It seems like a really great project, but it's hard to start without at least a working example.

**Comment by reecebrend** [comment]
Hey guys, 

Thanks for pointing this out, I'll be taking a look at this and getting a new doc site built as soon as I can!

**Comment by reecebrend** [comment]
Right, a more up to date version of the guide is now live.

@BillMeyerRSA Just to let you know, the 'Tymly Dev' command is 'npm run docs:dev' as per the package.json (https://github.com/wmfs/tymly-website/blob/master/package.json#L24)

I hope I've cleared some of those things up, feel free to raise more issues if there's anything else.
