### ISSUE TITLE
Extend food hygiene blueprint's state-machine

### ISSUE THREAD

**Issue by meenahoda** [wmfs/tymly#48]
This state-machine currently only refreshes from a CSV file, assuming you have already converted the xml to csv. The state could include a conversion of the xml -> csv before passing that CSV to the  'importingCsvFiles' state which uses Supercopy.

Basically, should probably change the state-machine so it 'refresh-from-xml-file'. 

https://github.com/wmfs/tymly/blob/master/blueprints/food-hygiene-blueprint/state-machines/refresh-from-csv-file.json

**Comment by reecebrend** [comment]
New state in pg plugin perhaps?
So a state-machine importing XML into the DB could 'StartAt' a 'convertToCsv' state, then an 'importingCsvFiles' following?

**Comment by meenahoda** [comment]
There is already a state in flobot-etl-plugin named 'processing-xml-files'. It seems to be all commented out, so I'm guessing we could maybe use this state to call the xml2csv package?
@timneedham yay or nay?
