### ISSUE TITLE
Seed data propertyNames array requires column names instead of propery names

### ISSUE THREAD

**Issue by jazz-b** [wmfs/tymly#50]
The loading of seed data is configured via json files in a /seed-data folder (inside a blueprint).  In the aforementioned json files, there is a property array called "propertyNames" - which holds a list of properties that will be loaded with data (defined later).

Unfortunately, the property names, unintuitively, need to be defined in snake-case (actual database column names instead of model property names).

**Comment by meenahoda** [comment]
Closed... See:
https://github.com/wmfs/tymly/commit/4eaef1c384fac0936297a3d6c045d1fad50892b9
https://github.com/wmfs/tymly/commit/3071ec5ca4246feecd026f2c2b1e4a147bb93899
