### ISSUE TITLE
relationize: Auto-generate indexes to support meta columns

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#54]
## Overview

Currently, our [relationize](https://github.com/wmfs/tymly/tree/master/packages/relationize) package automatically adds some "meta" column definitions to any PostgreSQL tables it deems necessary to create, for example:

* `_created`
* `_created_by`
* `_modified`
* `_modified_by`

__See here:__
https://github.com/wmfs/tymly/blob/master/packages/relationize/lib/parser.js#L239-L269

__These columns should also be accompanied with their own _index_ definitions too.__

Currently indexes are explicitly defined and added here:

https://github.com/wmfs/tymly/blob/master/packages/relationize/lib/parser.js#L23-L31

Somewhere around  where that happens, we should also add additional indexes for our 4 "meta" columns too.

## Tests/Outcome

So in our tests currently, some tables feature indexes in the expected output already:

https://github.com/wmfs/tymly/blob/master/packages/relationize/test/basic-tests.js#L123-L132

* After successful completion of this issue, we'd expect all tables to feature at least 4 indexes (one per meta column).
* So continuing this `person` table example, we'd expect to see additional indexes defined, such as:

``` json
{
  "person_created_idx": {
    "columns": [
      "_created"
    ],
    "unique": false,
    "method": "btree"
  }
}
```

**Comment by meenahoda** [comment]
Added the following lines before indexes.forEach(...) in relationize\lib\parser.js:
`// Add indexes for meta columns`
`    indexes.push({columns: ['_created'], unique: false})`
`    indexes.push({columns: ['_created_by'], unique: false})`
`    indexes.push({columns: ['_modified'], unique: false})`
`    indexes.push({columns: ['_modified_by'], unique: false})`

which will produce an example statement:
`CREATE INDEX ssi_created_by_idx ON wmfs.ssi USING btree (created_by);`

The only problem here is the column 'created_by' (at the end of the statement) doesn't exist as it should be _created_by in those brackets. It's losing the trailing underscores which is an issue I have come across before in the conversion between column names/property name and before the _.camelCase function was causing those lost underscores.
I think it might be somewhere in pg-diff-sync where it's generating the index statement that might need a fix in there...

**Comment by meenahoda** [comment]
https://github.com/wmfs/tymly/commit/fb2236a8c9bfe16bd5608cc30aef3908d22ec22e#diff-1b63e02c5c341ea58f8e38cf8e41bb84

Added a case statement to check for the meta columns to readjust their column names.

This might not be the best fix long-term as we're probably going to come across this issues again with the trailing underscores...
