### ISSUE TITLE
Validate category references 

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#59]
If a form/board/searchDoc etc. refers to an undefined category, then things can  go awry.
We should check such references refer to known categories, and generate boot-time errors when target categories can't be found.

**Comment by meenahoda** [comment]
Included a reference property for categories:
https://github.com/wmfs/tymly/blob/33767420ae4d489853e8c0de65b1f30b00850c14/packages/tymly/lib/plugin/components/services/categories/index.js#L84-L86
Therefore anywhere that has a 'categories' array will be processed to check the categories they refer to exist.
