### ISSUE TITLE
Tymly - exportingCsvDeltaFile state needs refactor

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#6]
Currently, state config looks like:

```
{
  "exportingCsvDeltaFile": {
    "options": {
      "since": "2000-07-16T20:37:26.847Z",
      "createdColumnName": "_created",
      "modifiedColumnName": "_modified",
      "actionAliases": {
        "insert": "u",
        "update": "u",
        "delete": "d"
      },
      "tables": [
        {
          "tableName": "people",
          "csvColumns": [
            "PERSON",
            "$ACTION",
            "$ROW_NUM",
            "@social_security_id",
            "@first_name",
            "@last_name",
            "@age"
          ]
        }
      ]
    }
  }
}
```

But that's not inferring anything from the blueprint/model.

* Should talk in **models** and **properties** (not tables and columns)
* The created/modified columns should at least default to _created and _modified (perhaps keep open the opportunity to work with non-Flobot-generated tables)
* Opportunity to check @properties are defined in the model?
* Infer schema/namespace
* And reduce the cruft and go straight to the columns...
* Need to ensure getting `getOptions()`  is used so `since` cqan be expressed via a Flobot command
**Something more like:**

```
{
  "exportingCsvDeltaFile": {
    "options": {
      "since": "2000-07-16T20:37:26.847Z",
      "actionAliases": {
        "insert": "u",
        "update": "u",
        "delete": "d"
      },
      "csvExtracts": {
        "people": [
            "PERSON",
            "$ACTION",
            "$ROW_NUM",
            "@social_security_id",
            "@first_name",
            "@last_name",
            "@age"          
        ]
      }
    }
  }
}
```

**Comment by meenahoda** [comment]
https://github.com/wmfs/tymly/commit/24a2801a85abd216b22a25d8888da048aee478c6

The package now refers to models/properties. 
The name space still needs to be inferred from somewhere rather than being in options and needs a way of working out what action to append.
https://github.com/wmfs/tymly/blob/master/packages/pg-delta-file/lib/Transformer.js#L27

**Comment by meenahoda** [comment]
Although namespace can be inferred from the context in the state resource run:
https://github.com/wmfs/tymly/blob/master/plugins/tymly-pg-plugin/lib/components/state-resources/exporting-csv-delta-file/index.js#L21
