### ISSUE TITLE
Validate `resourceConfig`

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#60]
It is possible to provide JSON Schema definitions for state resources:

https://github.com/wmfs/tymly/blob/master/plugins/tymly-etl-plugin/lib/components/state-resources/processing-csv-files/schema.json

We need to ensure all state resources are supplied with an accurate schema, and Statebox should be upgraded to validate `resourceConfig` objects against such a schema if present. If validation fails, then Statebox should throw an error when building a State Machine.

**Comment by meenahoda** [comment]
https://github.com/wmfs/tymly/commit/aa8f076d87a8aa168678f4a01ec6dca18272b0a7

See the following commit of an example for how to include the schema to validate your resource config against: https://github.com/wmfs/tymly/commit/5276bb37c3c23814c495b02d98a90271e2769783

In init() you need to assign the schema to this.schema, which is picked up and compared against the resource config of the state machine when the state machine is created.
If the resource config doesn't contain all the 'required' properties then you will see this error: "Resource Config missing required properties in stateMachine '...'"
