### ISSUE TITLE
Tymly - Functions service needs API

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#7]
To access an actual function is painful:

https://github.com/wmfs/tymly/blob/master/plugins/flobot-pg-plugin/lib/components/states/synchronizingTable/index.js#L15

How about: getFunction() to make things easier?

**Comment by meenahoda** [comment]
https://github.com/wmfs/tymly/commit/27d26b228c24b9ff626f9fc6c5ec589394a5c593
