### ISSUE TITLE
Express plugin API test

### ISSUE THREAD

**Issue by AronM28** [wmfs/tymly#71]
http://headers.jsontest.com (https://github.com/jsontest/jsontest) looks to be unreliable for testing API in tymly-express-plugin (https://github.com/wmfs/tymly/blob/master/plugins/tymly-express-plugin/test/express-spec.js)

Need something more suitable as an alternative that has better up time.

e.g. 

https://github.com/julien-lafont/Mocky 
https://github.com/typicode/jsonplaceholder

**Comment by jazz-b** [comment]
You know, I believe the express plugin provides a HTTP server to serve static content - maybe we can use that to serve test json for the purposes of this test?

**Comment by reecebrend** [comment]
I've amended the test to just query the API for the user's remit, similar to the previous test but using the actual state machine this time
