### ISSUE TITLE
Tymly-runner to watch $TYMLY_BLUEPRINTS_PATH ?

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#83]
Might be good to enhance [tymly-runner](https://github.com/wmfs/tymly/tree/master/packages/tymly-runner) to have a development mode which watches the various blueprint directories defined in `$TYMLY_BLUEPRINTS_PATH` and reboots itself on spotting _something_ has changed.

* The idea is to aid _blueprint_ development... spin-up **tymly-runner**, and leave it all day while hacking around with blueprints.
* Seem to be some good packages out there such as [watch](https://www.npmjs.com/package/watch) ?

**Comment by reecebrend** [comment]
https://github.com/wmfs/tymly/commit/4d51788fc1f8a41e59cf5574f740a4c71ec79588

I've added in a script to run tymly-runner using nodemon, it currently just watches the blueprints and private blueprints dirs and restarts on changing

We can set up a run config in webstorm, as an npm test with the same environment variables as we are currently using, but specify the script as 'start-nodemon'
